plugins {
    id 'application'
}

group = "org.cland.hello"
version = "0.1.0"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

application {
    mainClass = 'org.cland.hello.ClandHello'
    applicationName = 'cland-hello'
}
